/* sample_data.js — Replace with classified_alerts.json content for production */

const SAMPLE_DATA = {
  metadata: {
    model: "SecureBERT 2.0 + LoRA",
    total_alerts: 20,
    threats_found: 13,
    benign_filtered: 7,
    threat_rate: 65.0,
    accuracy: null,
    labeled: false,
    avg_time_per_alert_ms: 12.0,
    generated_at: new Date().toISOString(),
  },
  alerts: [
    { id: 1, source_category: "cloud", prediction: "threat", confidence: 0.9991, threat_probability: 0.9991, alert_text: "[cloud] Cloud event (aws:cloudtrail): RunInstances | from 139.198.18.205 | on host splunk.froth.ly", actual_label: "unknown", rule_summary: { key_fields: { event: "RunInstances", source_ip: "139.198.18.205" }, analyst_note: "Unauthorized EC2 instance launch. Possible crypto mining." }},
    { id: 2, source_category: "windows", prediction: "threat", confidence: 0.9987, threat_probability: 0.9987, alert_text: "[windows] A new process has been created. | Security ID: NT AUTHORITY\\SYSTEM | Account Name: BSTOLL-L$ | Process Name: cmd.exe | Command Line: cmd.exe /c wmic os get LocalDateTime", actual_label: "unknown", rule_summary: { key_fields: { event: "Process created", process: "cmd.exe", account: "BSTOLL-L$" }, analyst_note: "Suspicious process execution. Review command line." }},
    { id: 3, source_category: "network", prediction: "threat", confidence: 0.9962, threat_probability: 0.9962, alert_text: "[network] Network event (stream:tcp) | from 167.114.13.150:44832 to 172.31.12.76:22 | bytes_in=2269 bytes_out=3625", actual_label: "unknown", rule_summary: { key_fields: { connection: "167.114.13.150 -> 172.31.12.76:22", traffic: "bytes_in=2269 bytes_out=3625" }, analyst_note: "SSH connection from known attacker IP. Investigate." }},
    { id: 4, source_category: "linux", prediction: "threat", confidence: 0.9978, threat_probability: 0.9978, alert_text: "[linux] Aug 20 09:08:51 ip-172-31-12-76 sshd[9003]: input_userauth_request: invalid user administrues [preauth]", actual_label: "unknown", rule_summary: { key_fields: { service: "sshd", event: "invalid user: administrues" }, analyst_note: "SSH brute force — invalid username. Check source IP." }},
    { id: 5, source_category: "cloud", prediction: "threat", confidence: 0.9945, threat_probability: 0.9945, alert_text: "[cloud] Cloud event (aws:cloudtrail): CreateAccessKey | from 35.153.154.221 | on host splunk.froth.ly", actual_label: "unknown", rule_summary: { key_fields: { event: "CreateAccessKey", source_ip: "35.153.154.221" }, analyst_note: "IAM modification. Possible backdoor creation." }},
    { id: 6, source_category: "windows", prediction: "threat", confidence: 0.9934, threat_probability: 0.9934, alert_text: "[windows] The Windows Filtering Platform has blocked a connection. | Application: svchost.exe | Direction: Outbound | Destination: 40.67.251.132", actual_label: "unknown", rule_summary: { key_fields: { event: "WFP blocked connection", application: "svchost.exe" }, analyst_note: "Connection blocked by WFP. Possible C2 attempt." }},
    { id: 7, source_category: "cloud", prediction: "threat", confidence: 0.9901, threat_probability: 0.9901, alert_text: "[cloud] Cloud event (aws:cloudtrail): CreateUser | from 35.153.154.221 | on host splunk.froth.ly", actual_label: "unknown", rule_summary: { key_fields: { event: "CreateUser", source_ip: "35.153.154.221" }, analyst_note: "IAM modification. Possible backdoor creation." }},
    { id: 8, source_category: "cloud", prediction: "threat", confidence: 0.9889, threat_probability: 0.9889, alert_text: "[cloud] Cloud event (aws:cloudtrail): ConsoleLogin | from 157.97.121.132 | on host splunk.froth.ly", actual_label: "unknown", rule_summary: { key_fields: { event: "ConsoleLogin", source_ip: "157.97.121.132" }, analyst_note: "Console login from external IP. Verify with owner." }},
    { id: 9, source_category: "windows", prediction: "threat", confidence: 0.9912, threat_probability: 0.9912, alert_text: "[windows] Special privileges assigned to new logon. | Security ID: NT AUTHORITY\\SYSTEM | Privileges: SeAssignPrimaryTokenPrivilege", actual_label: "unknown", rule_summary: { key_fields: { event: "Special privileges assigned", account: "SYSTEM" }, analyst_note: "Privilege escalation detected. Verify if expected." }},
    { id: 10, source_category: "windows", prediction: "threat", confidence: 0.9867, threat_probability: 0.9867, alert_text: "[windows] An account failed to log on. | Account Name: Guest | Logon Type: 3 | Failure Reason: Account disabled.", actual_label: "unknown", rule_summary: { key_fields: { event: "Failed logon", account: "Guest" }, analyst_note: "Failed authentication. Check for brute force." }},
    { id: 11, source_category: "linux", prediction: "threat", confidence: 0.9823, threat_probability: 0.9823, alert_text: "[linux] Aug 20 11:37:04 ip-172-16-0-178 sshd[27438]: Invalid user test from 138.122.255.144 port 33043", actual_label: "unknown", rule_summary: { key_fields: { service: "sshd", source_ip: "138.122.255.144" }, analyst_note: "SSH brute force — invalid username. Check source IP." }},
    { id: 12, source_category: "network", prediction: "threat", confidence: 0.9756, threat_probability: 0.9756, alert_text: "[network] Network event (stream:tcp) | from 221.194.47.236:51286 to 172.31.12.76:22 | bytes_in=222 bytes_out=592", actual_label: "unknown", rule_summary: { key_fields: { connection: "221.194.47.236 -> 172.31.12.76:22" }, analyst_note: "SSH connection from known attacker IP. Investigate." }},
    { id: 13, source_category: "windows", prediction: "threat", confidence: 0.9876, threat_probability: 0.9876, alert_text: "[windows] A service was installed in the system. | Service Name: MpKsl2d84a0f7 | Account: BSTOLL-L$", actual_label: "unknown", rule_summary: { key_fields: { event: "Service installed", service: "MpKsl2d84a0f7" }, analyst_note: "New service installed. Check for persistence." }},
    { id: 14, source_category: "windows", prediction: "benign", confidence: 0.9994, threat_probability: 0.0006, alert_text: "[windows] The Windows Filtering Platform has permitted a connection. | Application: chrome.exe | Direction: Outbound", actual_label: "unknown", rule_summary: { key_fields: { event: "WFP permitted connection", application: "chrome.exe" }, analyst_note: "Normal Windows activity. No action required." }},
    { id: 15, source_category: "cloud", prediction: "benign", confidence: 0.9988, threat_probability: 0.0012, alert_text: "[cloud] Cloud event (aws:cloudtrail): DescribeInstances | from 34.215.24.225", actual_label: "unknown", rule_summary: { key_fields: { event: "DescribeInstances" }, analyst_note: "Normal cloud API activity." }},
    { id: 16, source_category: "linux", prediction: "benign", confidence: 0.9997, threat_probability: 0.0003, alert_text: "[linux] Aug 20 13:38:02 hoth osqueryd[4282]: Error casting status () to BIGINT", actual_label: "unknown", rule_summary: { key_fields: { service: "osqueryd" }, analyst_note: "Normal Linux system activity." }},
    { id: 17, source_category: "network", prediction: "benign", confidence: 0.9991, threat_probability: 0.0009, alert_text: "[network] Network event (stream:udp) | from 172.16.0.178:56874 to 172.16.0.2:53 | bytes_in=75 bytes_out=91", actual_label: "unknown", rule_summary: { key_fields: { connection: "172.16.0.178 -> 172.16.0.2:53 (DNS)" }, analyst_note: "Normal DNS query traffic." }},
    { id: 18, source_category: "windows", prediction: "benign", confidence: 0.9982, threat_probability: 0.0018, alert_text: "[windows] A privileged service was called. | Account: PeatCerf | Service: Security", actual_label: "unknown", rule_summary: { key_fields: { event: "Privileged service called", account: "PeatCerf" }, analyst_note: "Normal Windows activity. No action required." }},
    { id: 19, source_category: "cloud", prediction: "benign", confidence: 0.9976, threat_probability: 0.0024, alert_text: "[cloud] Cloud event (aws:cloudtrail): GetBucketLogging | from 34.215.24.225", actual_label: "unknown", rule_summary: { key_fields: { event: "GetBucketLogging" }, analyst_note: "Normal cloud API activity." }},
    { id: 20, source_category: "network", prediction: "benign", confidence: 0.9985, threat_probability: 0.0015, alert_text: "[network] Network event (stream:ip) | from 192.168.247.131 to 192.168.247.2 | bytes_in=100 bytes_out=175", actual_label: "unknown", rule_summary: { key_fields: { connection: "192.168.247.131 -> 192.168.247.2" }, analyst_note: "Normal internal network traffic." }},
  ]
};
